package hot100

import "interview-memory-agent/backend/internal/domain/question"

// Manifest is this application's reviewed Hot 100 catalog snapshot. It
// intentionally carries metadata and canonical links only, never problem text
// or solutions. Update it explicitly when the upstream plan changes.
var Manifest = []Entry{
	{1, "two-sum", "两数之和", question.DifficultyEasy, "哈希"}, {49, "group-anagrams", "字母异位词分组", question.DifficultyMedium, "哈希"}, {128, "longest-consecutive-sequence", "最长连续序列", question.DifficultyMedium, "哈希"},
	{15, "3sum", "三数之和", question.DifficultyMedium, "双指针"}, {42, "trapping-rain-water", "接雨水", question.DifficultyHard, "双指针"}, {11, "container-with-most-water", "盛最多水的容器", question.DifficultyMedium, "双指针"}, {283, "move-zeroes", "移动零", question.DifficultyEasy, "双指针"},
	{438, "find-all-anagrams-in-a-string", "找到字符串中所有字母异位词", question.DifficultyMedium, "滑动窗口"}, {3, "longest-substring-without-repeating-characters", "无重复字符的最长子串", question.DifficultyMedium, "滑动窗口"},
	{560, "subarray-sum-equals-k", "和为 K 的子数组", question.DifficultyMedium, "子串"}, {76, "minimum-window-substring", "最小覆盖子串", question.DifficultyHard, "子串"}, {239, "sliding-window-maximum", "滑动窗口最大值", question.DifficultyHard, "子串"},
	{56, "merge-intervals", "合并区间", question.DifficultyMedium, "普通数组"}, {53, "maximum-subarray", "最大子数组和", question.DifficultyMedium, "普通数组"}, {41, "first-missing-positive", "缺失的第一个正数", question.DifficultyHard, "普通数组"}, {189, "rotate-array", "轮转数组", question.DifficultyMedium, "普通数组"}, {238, "product-of-array-except-self", "除自身以外数组的乘积", question.DifficultyMedium, "普通数组"},
	{240, "search-a-2d-matrix-ii", "搜索二维矩阵 II", question.DifficultyMedium, "矩阵"}, {48, "rotate-image", "旋转图像", question.DifficultyMedium, "矩阵"}, {73, "set-matrix-zeroes", "矩阵置零", question.DifficultyMedium, "矩阵"}, {54, "spiral-matrix", "螺旋矩阵", question.DifficultyMedium, "矩阵"},
	{25, "reverse-nodes-in-k-group", "K 个一组翻转链表", question.DifficultyHard, "链表"}, {146, "lru-cache", "LRU 缓存", question.DifficultyMedium, "链表"}, {24, "swap-nodes-in-pairs", "两两交换链表中的节点", question.DifficultyMedium, "链表"}, {2, "add-two-numbers", "两数相加", question.DifficultyMedium, "链表"}, {19, "remove-nth-node-from-end-of-list", "删除链表的倒数第 N 个结点", question.DifficultyMedium, "链表"}, {206, "reverse-linked-list", "反转链表", question.DifficultyEasy, "链表"}, {23, "merge-k-sorted-lists", "合并 K 个升序链表", question.DifficultyHard, "链表"}, {21, "merge-two-sorted-lists", "合并两个有序链表", question.DifficultyEasy, "链表"}, {234, "palindrome-linked-list", "回文链表", question.DifficultyEasy, "链表"}, {148, "sort-list", "排序链表", question.DifficultyMedium, "链表"}, {141, "linked-list-cycle", "环形链表", question.DifficultyEasy, "链表"}, {142, "linked-list-cycle-ii", "环形链表 II", question.DifficultyMedium, "链表"}, {160, "intersection-of-two-linked-lists", "相交链表", question.DifficultyEasy, "链表"}, {138, "copy-list-with-random-pointer", "随机链表的复制", question.DifficultyMedium, "链表"},
	{230, "kth-smallest-element-in-a-bst", "二叉搜索树中第 K 小的元素", question.DifficultyMedium, "二叉树"}, {124, "binary-tree-maximum-path-sum", "二叉树中的最大路径和", question.DifficultyHard, "二叉树"}, {114, "flatten-binary-tree-to-linked-list", "二叉树展开为链表", question.DifficultyMedium, "二叉树"}, {94, "binary-tree-inorder-traversal", "二叉树的中序遍历", question.DifficultyEasy, "二叉树"}, {199, "binary-tree-right-side-view", "二叉树的右视图", question.DifficultyMedium, "二叉树"}, {102, "binary-tree-level-order-traversal", "二叉树的层序遍历", question.DifficultyMedium, "二叉树"}, {104, "maximum-depth-of-binary-tree", "二叉树的最大深度", question.DifficultyEasy, "二叉树"}, {236, "lowest-common-ancestor-of-a-binary-tree", "二叉树的最近公共祖先", question.DifficultyMedium, "二叉树"}, {543, "diameter-of-binary-tree", "二叉树的直径", question.DifficultyEasy, "二叉树"}, {105, "construct-binary-tree-from-preorder-and-inorder-traversal", "从前序与中序遍历序列构造二叉树", question.DifficultyMedium, "二叉树"}, {101, "symmetric-tree", "对称二叉树", question.DifficultyEasy, "二叉树"}, {108, "convert-sorted-array-to-binary-search-tree", "将有序数组转换为二叉搜索树", question.DifficultyEasy, "二叉树"}, {226, "invert-binary-tree", "翻转二叉树", question.DifficultyEasy, "二叉树"}, {437, "path-sum-iii", "路径总和 III", question.DifficultyMedium, "二叉树"}, {98, "validate-binary-search-tree", "验证二叉搜索树", question.DifficultyMedium, "二叉树"},
	{208, "implement-trie-prefix-tree", "实现 Trie（前缀树）", question.DifficultyMedium, "图论"}, {200, "number-of-islands", "岛屿数量", question.DifficultyMedium, "图论"}, {994, "rotting-oranges", "腐烂的橘子", question.DifficultyMedium, "图论"}, {207, "course-schedule", "课程表", question.DifficultyMedium, "图论"},
	{51, "n-queens", "N 皇后", question.DifficultyHard, "回溯"}, {46, "permutations", "全排列", question.DifficultyMedium, "回溯"}, {131, "palindrome-partitioning", "分割回文串", question.DifficultyMedium, "回溯"}, {79, "word-search", "单词搜索", question.DifficultyMedium, "回溯"}, {78, "subsets", "子集", question.DifficultyMedium, "回溯"}, {22, "generate-parentheses", "括号生成", question.DifficultyMedium, "回溯"}, {17, "letter-combinations-of-a-phone-number", "电话号码的字母组合", question.DifficultyMedium, "回溯"}, {39, "combination-sum", "组合总和", question.DifficultyMedium, "回溯"},
	{34, "find-first-and-last-position-of-element-in-sorted-array", "在排序数组中查找元素的第一个和最后一个位置", question.DifficultyMedium, "二分查找"}, {4, "median-of-two-sorted-arrays", "寻找两个正序数组的中位数", question.DifficultyHard, "二分查找"}, {153, "find-minimum-in-rotated-sorted-array", "寻找旋转排序数组中的最小值", question.DifficultyMedium, "二分查找"}, {74, "search-a-2d-matrix", "搜索二维矩阵", question.DifficultyMedium, "二分查找"}, {35, "search-insert-position", "搜索插入位置", question.DifficultyEasy, "二分查找"}, {33, "search-in-rotated-sorted-array", "搜索旋转排序数组", question.DifficultyMedium, "二分查找"},
	{394, "decode-string", "字符串解码", question.DifficultyMedium, "栈"}, {155, "min-stack", "最小栈", question.DifficultyMedium, "栈"}, {20, "valid-parentheses", "有效的括号", question.DifficultyEasy, "栈"}, {84, "largest-rectangle-in-histogram", "柱状图中最大的矩形", question.DifficultyHard, "栈"}, {739, "daily-temperatures", "每日温度", question.DifficultyMedium, "栈"},
	{347, "top-k-frequent-elements", "前 K 个高频元素", question.DifficultyMedium, "堆"}, {295, "find-median-from-data-stream", "数据流的中位数", question.DifficultyHard, "堆"}, {215, "kth-largest-element-in-an-array", "数组中的第 K 个最大元素", question.DifficultyMedium, "堆"},
	{121, "best-time-to-buy-and-sell-stock", "买卖股票的最佳时机", question.DifficultyEasy, "贪心"}, {763, "partition-labels", "划分字母区间", question.DifficultyMedium, "贪心"}, {55, "jump-game", "跳跃游戏", question.DifficultyMedium, "贪心"}, {45, "jump-game-ii", "跳跃游戏 II", question.DifficultyMedium, "贪心"},
	{152, "maximum-product-subarray", "乘积最大子数组", question.DifficultyMedium, "动态规划"}, {416, "partition-equal-subset-sum", "分割等和子集", question.DifficultyMedium, "动态规划"}, {139, "word-break", "单词拆分", question.DifficultyMedium, "动态规划"}, {279, "perfect-squares", "完全平方数", question.DifficultyMedium, "动态规划"}, {198, "house-robber", "打家劫舍", question.DifficultyMedium, "动态规划"}, {32, "longest-valid-parentheses", "最长有效括号", question.DifficultyHard, "动态规划"}, {300, "longest-increasing-subsequence", "最长递增子序列", question.DifficultyMedium, "动态规划"}, {118, "pascals-triangle", "杨辉三角", question.DifficultyEasy, "动态规划"}, {70, "climbing-stairs", "爬楼梯", question.DifficultyEasy, "动态规划"}, {322, "coin-change", "零钱兑换", question.DifficultyMedium, "动态规划"},
	{62, "unique-paths", "不同路径", question.DifficultyMedium, "多维动态规划"}, {64, "minimum-path-sum", "最小路径和", question.DifficultyMedium, "多维动态规划"}, {1143, "longest-common-subsequence", "最长公共子序列", question.DifficultyMedium, "多维动态规划"}, {5, "longest-palindromic-substring", "最长回文子串", question.DifficultyMedium, "多维动态规划"}, {72, "edit-distance", "编辑距离", question.DifficultyHard, "多维动态规划"},
	{31, "next-permutation", "下一个排列", question.DifficultyMedium, "技巧"}, {136, "single-number", "只出现一次的数字", question.DifficultyEasy, "技巧"}, {169, "majority-element", "多数元素", question.DifficultyEasy, "技巧"}, {287, "find-the-duplicate-number", "寻找重复数", question.DifficultyMedium, "技巧"}, {75, "sort-colors", "颜色分类", question.DifficultyMedium, "技巧"},
}
